run:
  timeout: 5m
  go: '1.23'

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  gofmt:
    simplify: true
  golint:
    min-confidence: 0.8
  govet:
    check-shadowing: true
  misspell:
    locale: US
  unused:
    check-exported: false

linters:
  enable:
    - gocyclo
    - goconst
    - gofmt
    - goimports
    - golint
    - govet
    - ineffassign
    - misspell
    - unused
    - staticcheck
    - errcheck
    - gosimple
    - typecheck
  disable:
    - deadcode
    - varcheck
    - structcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
