apiVersion: gpgen.dev/v1
kind: Pipeline
metadata:
  name: gpgen-build-pipeline
  annotations:
    gpgen.dev/validation-mode: relaxed
    gpgen.dev/description: "Go service pipeline"
spec:
  template: go-service
  inputs:
    goVersion: "1.24"
    testCommand: "go test ./..."
    buildCommand: "go build -o bin/gpgen ./cmd/gpgen"
    platforms: "linux/amd64,darwin/amd64"

  # Add custom steps here
  customSteps: []

  # Environment-specific configurations
  environments:
    staging:
      annotations:
        gpgen.dev/validation-mode: strict
      inputs:
        testCommand: "go test -race ./..."

    production:
      annotations:
        gpgen.dev/validation-mode: strict
      inputs:
        goVersion: "1.24"
        testCommand: "go test -race -cover ./..."
