name: gpgen-build-pipeline
"on":
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          cache: "true"
          go-version: "1.24"
      - name: Run tests
        run: go test ./...
      - name: Build service
        run: go build -o bin/gpgen ./cmd/gpgen
